component:
 product

about:
    商品列表

author:
  ice-yy


url3:basepath + "/app/productslist", //货架接口


   示例：
   <c-product-list callback='true' :type='item2.type' :url='url3' :params='{id:item2.shelf_id}' v-for="item2 in item.list"></c-product-list>

   备注：
   :type='item2.type'    type有三个参数 big、small、''
   :url='url3'    url是通过货架id进行请求的地址 
   :params='{id:item2.shelf_id}'  请求得到的货架id
   v-for="item2 in item.list    list是货架id
   
例子：
"list": [{
        "shelf_id": 11,
        "type":"big"
      }, {
        "shelf_id": 22,
        "type":"small"
      }, {
        "shelf_id": 33,
        "type":"big"
      }, {
        "shelf_id": 44,
        "type":""
      }]
      

callback='true'  会出发handle回调